apiVersion: apps/v1
kind: {{ .Values.deploy_type | default "DaemonSet" }}
metadata:
  name: k8s-ephemeral-storage-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
spec:
  {{- if eq .Values.deploy_type "Deployment" }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
    spec:
      serviceAccountName: k8s-ephemeral-storage-metrics
      containers:
        - name: metrics
          image: {{ .Values.image | default "registry.lab.com/k8s-ephemeral-storage-metrics" }}
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - name: http
              containerPort: {{ .Values.metrics_port | default "9100" }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /metrics
              port: {{ .Values.metrics_port | default "9100" }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /metrics
              port: {{ .Values.metrics_port | default "9100" }}
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.log_level | default "info" }}"
            - name: CURRENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: METRICS_PORT
              value: "{{ .Values.metrics_port | default "9100" }}"
            - name: CURRENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
